language: generic
sudo: required
services:
    - docker

env:
  global:
    - secure: "H+sd3XOedrSK0wgko1Nop1OEyafbKnSNeZCis7RYTs0x8hHOeCOE3V20277uwt/QrpOYqa7LrLPl+lh7woWNRIakm7uAHQ6RmSmst2r5MTYseu89m0eraoIdyFDdC4vNZAccj0MFVafOvYqT8h7N53DcsmMQ0QzxZJxOn/eBVYAA1/kDjoBCWpVD7fe/j1J2oPsjNQxcwkJbnjx1HXw53KUHSecqaQcccQb6xdXnMcAN/ZXKy9aCW5I+AC5ODKGtBYs2OfjRcTqXvWWS4MGbFRVOIFGXIz3143U8a+tpoYN3uggZu+P9y1FXTJIqXFNj8GaEvSBdaGsq/7ASWRxJ5hknEUjH8qW1HdrplnQ7yucC2+KR10NUJndQzawS5s+SprsIk2g3EvZPpiJwT0/HldTfizMDBdb/0GxHD9KH11vBetcHjghub389vUdL1uTFPdcsAO/nh7bSchvm9vNADRgDgUQdGCgvGddzPjGUBamATKfJUd1VWPUXe+T6AfHJd1hbsSubJ/ZNGPkMI+BPPAtuLV9xEjE84T/J2cKTqeuf1VQujSUpA34cyphyp2uD1iX9lQVK7dwdpErXyZTbmSudOyaTJSVN0YVvgQFL1mV/oG7hI7+hKfWDleK29lUj3zBn46ovWRctyV+CeFmRddzHoD8q1Cg3B3gJ6BHzEI8=" # DOCKER_USERNAME
    - secure: "ldNyJB9qffijru/IpPnVYaFxCdqAOIgW8NsJNW/B6NrQgK742jmACN5hnus/+iTbIcCOBzSwc/vttQCZB5J4NvzXGMcvOqaEH8UcQwZ18Z8px3Vu7FUU4d9cfrA2lgJKNqPUX+N2Uf4Nk4oZvNOd4p8sNAWEQ+CiCq0DUaJ0GIaP6I3j+nZnC4SoXk41J6XE6EFTtSZeXCnFfpH7GffrOLzJfMR7/clr3e18LNaT7aaQoifwCr4mCZVpnSZ9p1/IQvEi42X8klqpQ5W8blJzYsj2A1irtrU0LvknHB0RPADv08+5zWhRKcKQ/ZuHYZrS9t/43uJZ0NsvBmah+00bat1iHTfKu7dAewy2GBeCXpbu4CavWgltlU7gYfBADiFOxoIg5XtJwgDvCuMqCk8HnyY6Ci2PN9WxcGYUlSR5Z9aBpyv8Wt1Q3uRXtGpsNzESFvoE20UHZhT6s7LetKKb70t7XFg0KlaAWOf4nr6bo6T7hxm0AdCrsof2nESR20uhIi6w0ZFYw0fDNw/PkAAdO7z43kQJPTB5t67/IhtoCA7B67ZuvHz7LcgPh1TnKpQJFKsops/osJcbevAU46J4RAcp1QFQS2pY1N5B1fjrVFp4Jj589zlZUtOCU+862XykstN4qlLrCp9xwW2cAF92ZCvGZVsTid1LkwVx8xoJ5LA=" # DOCKER_PASSWORD

script: 
    - ls ./
before_deploy:
    - docker run --rm --privileged multiarch/qemu-user-static:register
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin   
deploy:
  provider: script
  script: 
    - if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then cd ./CometVisuBase && sudo ./hooks/build --noPush; else cd ./CometVisuBase && sudo ./hooks/build; fi
  skip_cleanup: true