language: generic
sudo: required
services:
    - docker
script:
    - ls ./
before_deploy:
    - docker run --rm --privileged multiarch/qemu-user-static:register
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script: 
    - if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then cd ./CometVisuBase && sudo ./hooks/build --noPush; else cd ./CometVisuBase && sudo ./hooks/build; fi
  skip_cleanup: true