name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      -
        name: Prepare
        id: prep
        run: |
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=vcs_ref::${GITHUB_SHA::8}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: directory list
        run:  ls -l -A && ls -l -A CometVisuBase
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./CometVisuBase
          file: CometVisuBase/Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: cometvisu/cometvisuabstractbase:newlatest
          build-args: |
            BUILD_DATE=${{ steps.prep.outputs.build_date }}
            VCS_REF=${{ steps.prep.outputs.vcs_ref }}
